[dir]
INPUT_BASE = /glade/campaign/acom/acom-weather/pfister/ANALYSIS/MetPlus/Install_rajesh
OUTPUT_BASE = {INPUT_BASE}/MET_output_WRF
STAGING_DIR={OUTPUT_BASE}/stage
MET_INSTALL_DIR = /glade/work/pfister/conda-envs/metplus_env
TMP_DIR = {OUTPUT_BASE}/tmp

[config]
CONF_DIR = /glade/campaign/acom/acom-weather/pfister/ANALYSIS/MetPlus/Install_rajesh


[user_env_vars]
MET_PYTHON_EXE = /glade/work/pfister/conda-envs/metplus_env/bin/python3

PRE_LOAD_CHROME = True
